name: Python Scraper

on:
  push:
    paths:
      - 'code/**.py'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Run scraper
      run: python code/run_all_scrapers.py
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Automated commit'
        commit_options: '--no-verify --all'
        branch: ${{ github.ref }}
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        repository: .
        commit_user_signingkey: ${{ secrets.COMMIT_SIGNING_KEY }}
        commit_bot_token: ${{ secrets.BOT_TOKEN }}
        push: true
